try{
    console.log(max)
}
catch(err)
{
    console.log(err.name)
    console.log(err.message )
    console.log(err.stack)

}